### ISSUE TITLE
pretrain model can not be reached

### ISSUE THREAD

**Issue by Kenneth-X** [voldemortX/DST-CBC#13]
hi,
http://vllab1.ucmerced.edu/~whung/adv-semi-seg/resnet101COCO-41f33a49.pth
can not be reached, can you upload it again?

**Comment by voldemortX** [comment]
I'll upload to Google drive in a few hours.

**Comment by voldemortX** [comment]
@Kenneth-X https://drive.google.com/file/d/14j4RoLqnfGeKaBN7m11u8XUnuov6PgYp/view?usp=sharing

**Comment by Kenneth-X** [comment]
@voldemortX thank you for your quick response

**Comment by voldemortX** [comment]
You are welcome. Feel free to contact again if you face further download issues.

**Comment by Kenneth-X** [comment]
@voldemortX thank you for your quick response
